#!/bin/bash

# Install freeside prereqs
# List culled from freeside repo file /debian/control

aptitude -y install \
  aspell-en \
  gnupg \
  ghostscript \
  gsfonts \
  gzip \
  latex-xcolor \
  libbusiness-creditcard-perl \
  libcache-cache-perl \
  libcache-simple-timedexpiry-perl \
  libchart-perl \
  libclass-container-perl \
  libclass-data-inheritable-perl \
  libclass-returnvalue-perl \
  libcolor-scheme-perl \
  libcompress-zlib-perl \
  libconvert-binhex-perl \
  libcrypt-passwdmd5-perl \
  libcrypt-ssleay-perl \
  libcss-squish-perl \
  libdata-password-perl \
  libdate-manip-perl \
  libdbd-mysql-perl \
  libdbd-pg-perl \
  libdbi-perl \
  libdbix-dbschema-perl \
  libdbix-searchbuilder-perl \
  libdevel-stacktrace-perl \
  libdevel-symdump-perl \
  liberror-perl \
  libexcel-writer-xlsx-perl \
  libexception-class-perl \
  libfile-counterfile-perl \
  libfile-rsync-perl \
  libfont-afm-perl \
  libfreezethaw-perl \
  libfrontier-rpc-perl \
  libgd-gd2-perl \
  libgd-graph-perl \
  libhtml-format-perl \
  libhtml-mason-perl \
  libhtml-parser-perl \
  libhtml-scrubber-perl \
  libhtml-tagset-perl \
  libhtml-tree-perl \
  libhtml-widgets-selectlayers-perl \
  libio-stringy-perl \
  libipc-run-perl \
  libipc-run3-perl \
  libipc-sharelite-perl \
  libjavascript-rpc-perl \
  libjson-perl \
  liblingua-en-inflect-perl \
  liblingua-en-nameparse-perl \
  liblocale-gettext-perl \
  liblocale-maketext-fuzzy-perl \
  liblocale-maketext-lexicon-perl \
  liblocale-subcountry-perl \
  liblog-dispatch-perl \
  libmailtools-perl \
  libmime-tools-perl \
  libmodule-versions-report-perl \
  libnet-daemon-perl \
  libnet-ping-external-perl \
  libnet-scp-perl \
  libnet-ssh-perl \
  libnet-whois-raw-perl \
  libnetaddr-ip-perl \
  libnumber-format-perl \
  libpam-modules \
  libpam-runtime \
  libpaper-utils \
  libparams-validate-perl \
  libparse-recdescent-perl \
  libpg-perl \
  libregexp-common-perl \
  libspreadsheet-writeexcel-perl \
  libstring-approx-perl \
  libstring-shellquote-perl \
  libterm-readkey-perl \
  libtest-inline-perl \
  libtext-autoformat-perl \
  libtext-charwidth-perl \
  libtext-csv-perl \
  libtext-iconv-perl \
  libtext-quoted-perl \
  libtext-reform-perl \
  libtext-template-perl \
  libtext-wrapi18n-perl \
  libtext-wrapper-perl \
  libtie-ixhash-perl \
  libtime-duration-perl \
  libtime-modules-perl \
  libtimedate-perl \
  libtree-simple-perl \
  libuniversal-require-perl \
  liburi-perl \
  libwant-perl \
  libwww-perl \
  libxml-parser-perl \
  libyaml-perl \
  lmodern \
  locales \
  lpr \
  mime-support \
  ntp \
  ntpdate \
  perl \
  perl-base \
  perl-modules \
  postgresql \
  postgresql-client \
  psutils \
  rsync \
  openssh-client \
  texlive \
  texlive-latex-extra \
  texinfo \
  ttf-bitstream-vera \
  fonts-dustin \
  libdatetime-perl \
  libdatetime-format-strptime-perl \
  libfile-slurp-perl \
  libspreadsheet-parseexcel-perl \
  libauthen-passphrase-perl \
  libnet-domain-tld-perl \
  libbusiness-us-usps-webtools-perl \
  libxml-simple-perl \
  libemail-sender-perl \
  libemail-sender-transport-smtp-tls-perl \
  libhtml-defang-perl \
  libdatetime-format-natural-perl \
  libcgi-pm-perl \
  libfile-sharedir-perl \
  libmodule-versions-report-perl \
  libtext-wikiformat-perl \
  libnet-server-perl \
  libhttp-server-simple-perl \
  libhtml-rewriteattributes-perl \
  libmime-types-perl \
  libperlio-eol-perl \
  libgnupg-interface-perl \
  libdata-ical-perl \
  libcalendar-simple-perl \
  libdatetime-set-perl \
  libhook-lexwrap-perl \
  libhttp-server-simple-mason-perl \
  libxml-rss-perl \
  libipc-run-safehandles-perl \
  libpoe-perl \
  libsoap-lite-perl \
  libhtml-tableextract-perl \
  libhtml-element-extended-perl \
  libcam-pdf-perl \
  libnet-openssh-perl \
  libgd-barcode-perl \
  sam2p \
  libsys-sigaction-perl \
  libgeo-googleearth-pluggable-perl \
  libgeo-coder-googlev3-perl \
  libnet-snmp-perl \
  libcrypt-openssl-rsa-perl \
  libregexp-common-perl \
  libnet-cidr-perl \
  libregexp-ipv6-perl \
  libhtml-quoted-perl \
  libtext-password-pronounceable-perl \
  libconvert-color-perl \
  liburi-perl \
  libhtml-rewriteattributes-perl \
  libregexp-common-net-cidr-perl \
  liblog-dispatch-perl \
  libdbix-searchbuilder-perl \
  libencode-perl \
  libhtml-mason-psgihandler-perl \
  libdate-simple-perl \
  libsnmp-perl \
  libemail-valid-perl \
  libio-string-perl \
  libnet-smtp-ssl-perl \
  libgeo-coder-googlev3-perl \
  libcam-pdf-perl \
  libnet-openssh-perl \
  libhtml-quoted-perl \
  libregexp-ipv6-perl \
  libregexp-common-net-cidr-perl \
  libexcel-writer-xlsx-perl \
  libgeo-googleearth-pluggable-perl \
  libhtml-mason-psgihandler-perl \
  libdate-simple-perl \
  libsnmp-perl \
  libparse-fixedlength-perl \
  libregexp-common-net-cidr-perl \
  libnet-mac-vendor-perl \
  libnet-https-any-perl \
  libapache2-authcookie-perl \
  liblocale-currency-format-perl \
  libhtml-formattext-withlinks-perl \
  libemail-address-perl \
  libemail-address-list-perl \
  libsymbol-global-name-perl \
  libdate-extract-perl \
  librole-basic-perl \
  libhtml-formattext-withlinks-andtables-perl \
  libcrypt-x509-perl \
  libdata-guid-perl \
  libparams-classify-perl \
  libcpanel-json-xs-perl \
  libarchive-zip-perl \
  libtry-tiny-perl \
  libnumber-phone-perl \
  libxml-libxml-simple-perl \
  libxml-writer-perl \
  libio-socket-ssl-perl \
  libmap-splat-perl \
  libdatetime-format-ical-perl \
  librest-client-perl \
  libgeo-streetaddress-us-perl \
  libbusiness-onlinepayment-perl \
  libnet-vitelity-perl \
  libnet-sslglue-perl \
  libexpect-perl \
  libspreadsheet-parsexlsx-perl \
  git \
  apache2 \
  libapache-session-perl \
  libapache-dbi-perl
