# Debian 8 with branch FREESIDE_3_BRANCH
Vagrant.configure('2') do |config|
    config.vm.box = 'debian/contrib-jessie64'
    config.vm.hostname = 'vagrant-deb8-fs3.lab'

    config.vm.network "public_network", ip: "192.168.1.52"

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.provision :init, type: "shell", path: "provision/initial.sh"
    config.vm.provision :fsprereqs, type: "shell", path: "provision/fs3-prereqs.sh"
    config.vm.provision :fssetup, type: "shell", path: "provision/fs3-setup.sh"
    config.vm.provision :freeradius, type: "shell", path: "provision/freeradius.sh"
end
