# Install Debian 8 with Freeside 4

Vagrant.configure('2') do |config|
    config.vm.box = 'bento/debian-8.7'
    config.vm.hostname = 'vagrant-deb8-master.lab'

    config.vm.network "public_network", ip: "192.168.1.51"

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end
    config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = 4096
      v.vmx["numvcpus"] = 2
    end

    config.vm.provision :init, type: "shell", path: "provision/initial.sh"
    config.vm.provision :fsprereqs, type: "shell", path: "provision/fs4-prereqs.sh"
    config.vm.provision :fssetup, type: "shell", path: "provision/fs4-setup.sh"
    config.vm.provision :fsselfserv, type: "shell", path: "provision/fs-selfservice.sh"
    config.vm.provision :freeradius, type: "shell", path: "provision/freeradius.sh"
end
