#!/bin/bash

# Install system prereqs for freeside

# Install prereqs
aptitude -y install \
    apache2 \
    git \
    libapache-dbi-perl \
    libapache-session-perl \
    libapache2-authcookie-perl \
    libapache2-mod-perl2 \
    libauthen-passphrase-perl \
    libbusiness-creditcard-perl \
    libbusiness-onlinepayment-perl \
    libbusiness-us-usps-webtools-perl \
    libc6-dev \
    libcache-cache-perl \
    libcam-pdf-perl \
    libcgi-emulate-psgi-perl \
    libcgi-psgi-perl \
    libchart-perl \
    libcolor-scheme-perl \
    libconvert-color-perl \
    libcpanel-json-xs-perl \
    libcrypt-openssl-rsa-perl \
    libcrypt-passwdmd5-perl \
    libcrypt-ssleay-perl \
    libcrypt-ssleay-perl \
    libcrypt-x509-perl \
    libcss-squish-perl \
    libdata-guid-perl \
    libdata-ical-perl \
    libdata-password-perl \
    libdate-extract-perl \
    libdate-manip-perl \
    libdate-simple-perl \
    libdatetime-format-ical-perl \
    libdatetime-format-natural-perl \
    libdatetime-format-strptime-perl \
    libdatetime-perl \
    libdatetime-set-perl \
    libdbd-pg-perl \
    libdbi-perl \
    libdbix-dbschema-perl \
    libdbix-searchbuilder-perl \
    libdbix-searchbuilder-perl \
    libemail-address-list-perl \
    libemail-address-list-perl \
    libemail-address-perl \
    libemail-sender-perl \
    libemail-sender-transport-smtp-tls-perl \
    libemail-valid-perl \
    libencode-perl \
    libexcel-writer-xlsx-perl \
    libexpect-perl \
    libfile-counterfile-perl \
    libfile-rsync-perl \
    libfile-sharedir-perl \
    libfile-slurp-perl \
    libfile-which-perl \
    libfile-which-perl \
    libfrontier-rpc-perl \
    libgd-barcode-perl \
    libgd-graph-perl \
    libgeo-coder-googlev3-perl \
    libgeo-googleearth-pluggable-perl \
    libgeo-streetaddress-us-perl \
    libgnupg-interface-perl \
    libhtml-defang-perl \
    libhtml-element-extended-perl \
    libhtml-formattext-withlinks-andtables-perl \
    libhtml-formattext-withlinks-perl \
    libhtml-mason-perl \
    libhtml-mason-psgihandler-perl \
    libhtml-parser-perl \
    libhtml-quoted-perl \
    libhtml-rewriteattributes-perl \
    libhtml-scrubber-perl \
    libhtml-table-perl \
    libhtml-tableextract-perl \
    libhtml-tagset-perl \
    libhtml-tree-perl \
    libhtml-widgets-selectlayers-perl \
    libio-string-perl \
    libio-stringy-perl \
    libipc-run-perl \
    libipc-run-safehandles-perl \
    libipc-run3-perl \
    libjson-perl \
    liblingua-en-inflect-perl \
    liblingua-en-nameparse-perl \
    liblocale-codes-perl \
    liblocale-currency-format-perl \
    liblocale-maketext-fuzzy-perl \
    liblocale-maketext-lexicon-perl \
    liblocale-subcountry-perl \
    liblog-dispatch-perl \
    libmailtools-perl \
    libmime-tools-perl \
    libmodule-refresh-perl \
    libmodule-versions-report-perl \
    libnet-cidr-perl \
    libnet-domain-tld-perl \
    libnet-https-any-perl \
    libnet-mac-vendor-perl \
    libnet-openssh-perl \
    libnet-ping-external-perl \
    libnet-ping-perl \
    libnet-snmp-perl \
    libnet-ssh-perl \
    libnet-vitelity-perl \
    libnet-whois-raw-perl \
    libnetaddr-ip-perl \
    libnumber-format-perl \
    libnumber-phone-perl \
    libparse-fixedlength-perl \
    libperlio-eol-perl \
    libplack-perl \
    libpoe-perl \
    libregexp-common-net-cidr-perl \
    libregexp-common-perl \
    libregexp-ipv6-perl \
    librest-client-perl \
    librole-basic-perl \
    libsnmp-perl \
    libsoap-lite-perl \
    libspreadsheet-writeexcel-perl \
    libstring-approx-perl \
    libstring-shellquote-perl \
    libsymbol-global-name-perl \
    libsys-sigaction-perl \
    libterm-readkey-perl \
    libtest-pod-coverage-perl \
    libtest-pod-perl \
    libtext-csv-perl \
    libtext-csv-xs-perl \
    libtext-password-pronounceable-perl \
    libtext-quoted-perl \
    libtext-template-perl \
    libtext-wikiformat-perl \
    libtext-wrapper-perl \
    libtie-ixhash-perl \
    libtime-duration-perl \
    libtime-parsedate-perl \
    libtimedate-perl \
    libtree-simple-perl \
    liburi-perl \
    libwww-perl \
    libxml-libxml-lazybuilder-perl \
    libxml-libxml-perl \
    libxml-libxml-simple-perl \
    libxml-rss-perl \
    libxml-simple-perl \
    libxml-writer-perl \
    postgresql
